// <auto-generated />
using System;
using HumanitaracApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HumanitaracApi.Migrations
{
    [DbContext(typeof(HumanitaracDbContext))]
    [Migration("20260304140238_AddMoreActivities")]
    partial class AddMoreActivities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("HumanitaracApi.Models.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = "a1",
                            Category = "Pomoć",
                            City = "Novi Pazar",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 959, DateTimeKind.Utc).AddTicks(7220),
                            Date = new DateTime(2026, 3, 1, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Podjela prehrambenih paketa.",
                            Title = "Distribucija hrane i higijene"
                        },
                        new
                        {
                            Id = "a2",
                            Category = "Edukacija",
                            City = "Sjenica",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 960, DateTimeKind.Utc).AddTicks(2720),
                            Date = new DateTime(2026, 2, 22, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Radionica o higijeni.",
                            Title = "Edukacija o sanitaciji"
                        },
                        new
                        {
                            Id = "a3",
                            Category = "Krizna pomoć",
                            City = "Tutin",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 960, DateTimeKind.Utc).AddTicks(3250),
                            Date = new DateTime(2026, 2, 12, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Prikupljanje potrepština.",
                            Title = "Prikupljanje pomoći"
                        },
                        new
                        {
                            Id = "a4",
                            Category = "Volontiranje",
                            City = "Beograd",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 960, DateTimeKind.Utc).AddTicks(3270),
                            Date = new DateTime(2026, 2, 2, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Čišćenje parka.",
                            Title = "Park Čišćenje"
                        },
                        new
                        {
                            Id = "a5",
                            Category = "Pomoć",
                            City = "Niš",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 960, DateTimeKind.Utc).AddTicks(3290),
                            Date = new DateTime(2026, 2, 27, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Obilazak i pomoć starijim sugrađanima u svakodnevnim aktivnostima.",
                            Title = "Podrška starijim osobama"
                        },
                        new
                        {
                            Id = "a6",
                            Category = "Edukacija",
                            City = "Kragujevac",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 960, DateTimeKind.Utc).AddTicks(3300),
                            Date = new DateTime(2026, 2, 17, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Kreativne radionice za djecu i mlade u lokalnoj biblioteci.",
                            Title = "Radionica kreativnog pisanja"
                        },
                        new
                        {
                            Id = "a7",
                            Category = "Volontiranje",
                            City = "Novi Sad",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 960, DateTimeKind.Utc).AddTicks(3310),
                            Date = new DateTime(2026, 2, 24, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Akcija sadnje 200 stabala u gradskom parku.",
                            Title = "Sadnja drveća"
                        },
                        new
                        {
                            Id = "a8",
                            Category = "Krizna pomoć",
                            City = "Prijepolje",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 960, DateTimeKind.Utc).AddTicks(3330),
                            Date = new DateTime(2026, 2, 7, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Prikupljanje tople odjeće i obuće za socijalno ugrožene porodice.",
                            Title = "Prikupljanje odjeće za zimu"
                        },
                        new
                        {
                            Id = "a9",
                            Category = "Pomoć",
                            City = "Beograd",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 960, DateTimeKind.Utc).AddTicks(3340),
                            Date = new DateTime(2026, 2, 20, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Organizacija besplatnih preventivnih zdravstvenih pregleda.",
                            Title = "Besplatni medicinski pregledi"
                        },
                        new
                        {
                            Id = "a10",
                            Category = "Edukacija",
                            City = "Novi Pazar",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 960, DateTimeKind.Utc).AddTicks(3350),
                            Date = new DateTime(2026, 2, 25, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(8020),
                            Description = "Besplatni kursevi osnova programiranja za nezaposlene mlade.",
                            Title = "IT obuka za nezaposlene"
                        });
                });

            modelBuilder.Entity("HumanitaracApi.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("HumanitaracApi.Models.Donation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("HumanitaracApi.Models.Participation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("HumanitaracApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "u_admin_1",
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 956, DateTimeKind.Utc).AddTicks(9190),
                            Email = "marko.ilic@example.com",
                            Name = "Marko Ilic",
                            Password = "adminpass1",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = "u_admin_2",
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 957, DateTimeKind.Utc).AddTicks(8640),
                            Email = "aleksandar.v@example.com",
                            Name = "Aleksandar Vukasnovic",
                            Password = "adminpass2",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = "u_user_1",
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 957, DateTimeKind.Utc).AddTicks(9050),
                            Email = "ilma.emrovic@example.com",
                            Name = "Ilma Emrovic",
                            Password = "userpass1",
                            Role = "User"
                        },
                        new
                        {
                            Id = "u_user_2",
                            CreatedAt = new DateTime(2026, 3, 4, 14, 2, 37, 957, DateTimeKind.Utc).AddTicks(9060),
                            Email = "aldina.avdic@example.com",
                            Name = "Aldina Avdic",
                            Password = "userpass2",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("HumanitaracApi.Models.Volunteer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("HumanitaracApi.Models.Participation", b =>
                {
                    b.HasOne("HumanitaracApi.Models.Activity", "Activity")
                        .WithMany("Participations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("HumanitaracApi.Models.Activity", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
