// <auto-generated />
using System;
using HumanitaracApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HumanitaracApi.Migrations
{
    [DbContext(typeof(HumanitaracDbContext))]
    [Migration("20260224200217_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("HumanitaracApi.Models.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = "a1",
                            Category = "Pomoć",
                            City = "Novi Pazar",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 2, 24, 20, 2, 17, 106, DateTimeKind.Utc).AddTicks(9860),
                            Date = new DateTime(2026, 2, 21, 20, 2, 17, 104, DateTimeKind.Utc).AddTicks(5850),
                            Description = "Podjela prehrambenih paketa.",
                            Title = "Distribucija hrane i higijene"
                        },
                        new
                        {
                            Id = "a2",
                            Category = "Edukacija",
                            City = "Sjenica",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 2, 24, 20, 2, 17, 107, DateTimeKind.Utc).AddTicks(8530),
                            Date = new DateTime(2026, 2, 14, 20, 2, 17, 104, DateTimeKind.Utc).AddTicks(5850),
                            Description = "Radionica o higijeni.",
                            Title = "Edukacija o sanitaciji"
                        },
                        new
                        {
                            Id = "a3",
                            Category = "Krizna pomoć",
                            City = "Tutin",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 2, 24, 20, 2, 17, 107, DateTimeKind.Utc).AddTicks(8960),
                            Date = new DateTime(2026, 2, 4, 20, 2, 17, 104, DateTimeKind.Utc).AddTicks(5850),
                            Description = "Prikupljanje potrepština.",
                            Title = "Prikupljanje pomoći"
                        },
                        new
                        {
                            Id = "a4",
                            Category = "Volontiranje",
                            City = "Beograd",
                            Completed = false,
                            CreatedAt = new DateTime(2026, 2, 24, 20, 2, 17, 107, DateTimeKind.Utc).AddTicks(8980),
                            Date = new DateTime(2026, 1, 25, 20, 2, 17, 104, DateTimeKind.Utc).AddTicks(5850),
                            Description = "Čišćenje parka.",
                            Title = "Park Čišćenje"
                        });
                });

            modelBuilder.Entity("HumanitaracApi.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("HumanitaracApi.Models.Donation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("HumanitaracApi.Models.Participation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("HumanitaracApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "u_admin_1",
                            CreatedAt = new DateTime(2026, 2, 24, 20, 2, 17, 104, DateTimeKind.Utc).AddTicks(6960),
                            Email = "marko.ilic@example.com",
                            Name = "Marko Ilic",
                            Password = "adminpass1",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = "u_admin_2",
                            CreatedAt = new DateTime(2026, 2, 24, 20, 2, 17, 105, DateTimeKind.Utc).AddTicks(760),
                            Email = "aleksandar.v@example.com",
                            Name = "Aleksandar Vukasnovic",
                            Password = "adminpass2",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = "u_user_1",
                            CreatedAt = new DateTime(2026, 2, 24, 20, 2, 17, 105, DateTimeKind.Utc).AddTicks(1100),
                            Email = "ilma.emrovic@example.com",
                            Name = "Ilma Emrovic",
                            Password = "userpass1",
                            Role = "User"
                        },
                        new
                        {
                            Id = "u_user_2",
                            CreatedAt = new DateTime(2026, 2, 24, 20, 2, 17, 105, DateTimeKind.Utc).AddTicks(1110),
                            Email = "aldina.avdic@example.com",
                            Name = "Aldina Avdic",
                            Password = "userpass2",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("HumanitaracApi.Models.Volunteer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("HumanitaracApi.Models.Participation", b =>
                {
                    b.HasOne("HumanitaracApi.Models.Activity", "Activity")
                        .WithMany("Participations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("HumanitaracApi.Models.Activity", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
